<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lst_resultsearch</name>
   <tag></tag>
   <elementGuidId>5ac59ca3-ec0c-4180-88f5-e2c19a7ebf60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2/a[contains(text(),'${text}')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
